In [3]:
import plotly as py
import pandas as pd

In [25]:
sofa = pd.read_csv("../croll/sofa_test.csv")

In [51]:
# import plotly.express as px
# data_canada = px.data.gapminder().query("country == 'Canada'")
# fig = px.bar(data_canada, x='year', y='pop')
# fig.show()

In [ ]:
data_canada = px.data.gapminder().query("country == 'Canada'")

In [55]:
df = px.data.iris()
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [56]:
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()

In [66]:
test = pd.DataFrame(sofa['0'].value_counts())
px.scatter(test, y="color=species")
# fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
# fig.show()

SyntaxError: unterminated string literal (detected at line 2) (3669811333.py, line 2)

In [61]:
dataframe(sofa['0'].value_counts())

NameError: name 'dataframe' is not defined

In [67]:
# Run this app with `python app.py` and
# visit http://127.0.0.1:8050/ in your web browser.

from dash import Dash, html, dcc
import plotly.express as px
import pandas as pd

app = Dash(__name__)

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for your data.
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1

C:\Users\yeana shin\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.

In [8]:
from dash import html

In [13]:
oh_test = pd.read_csv("oh_매출테스트.csv")

In [30]:
oh_test['결제가(판매비/조립비/선불)'][1:].astype(int).sum()

24485600

In [31]:
oh_test = pd.read_csv("oh_매출테스트.csv")
oh_test['결제가(판매비/조립비/선불)'][1:].astype(int).sum()

24485600

In [68]:
aaa = oh_test['상품명'][2:].value_counts().reset_index().head(5)
aaa

                                        index  상품명
0            DSAD114D 1400x700 컴퓨터데스크 5colors    9
1             DSAD212 1200x600 베이직데스크 5colors    9
2                    1000폭 수납형 모니터받침대 3colors    6
3  DSAD614P 1400폭 1인 노트북 책상 2colors + 빌트인 콘센트    5
4  DSAD612P 1200폭 1인 노트북 책상 3colors + 빌트인 콘센트    4

In [73]:
import plotly.graph_objects as go

aaa = oh_test['상품명'][2:].value_counts().reset_index().head(5)
labels = aaa['index']
values = aaa['상품명']

# Use `hole` to create a donut-like pie chart
fig = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.5 )])
fig.show()

In [2]:
from dash import Dash, dash_table
import pandas as pd
from collections import OrderedDict

data = OrderedDict(
    [
        ("Date", ["2015-01-01", "2015-10-24", "2016-05-10", "2017-01-10", "2018-05-10", "2018-08-15"]),
        ("Region", ["Montreal", "Toronto", "New York City", "Miami", "San Francisco", "London"]),
        ("Temperature", [1, -20, 3.512, 4, 10423, -441.2]),
        ("Humidity", [10, 20, 30, 40, 50, 60]),
        ("Pressure", [2, 10924, 3912, -10, 3591.2, 15]),
    ]
)
df = pd.DataFrame(data)

app = Dash(__name__)

app.layout = dash_table.DataTable(
    data=df.to_dict('records'),
    columns=[{'id': c, 'name': c} for c in df.columns]
)

if __name__ == '__main__':
    app.run_server(debug=True)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1